# ------------------------------------------------------------------------------
[tool.black]

line-length = 100


# ------------------------------------------------------------------------------
[tool.isort]

# Make base formatting compatible with black settings
profile = "black"
line_length = 100

skip = ["generated"]

# Add comments before each import group
import_heading_future = "Future libraries"
import_heading_stdlib = "Standard libraries"
import_heading_example_pythonpath = """\
Import before others since it modifies PYTHONPATH. pylint: disable=unused-import"""
import_heading_firstparty = "First party libraries"
import_heading_thirdparty = "Third party libraries"
import_heading_localfolder = "Local folder libraries"

# Change order so that "example_pythonpath" Python module, which is a "first party" import,
# is placed before "third party" imports.
# This is since that import updates PYTHONPATH, which is needed to find e.g. VUnit which is a
# third party import.
known_example_pythonpath = "tsfpga.examples.example_pythonpath"
sections = "FUTURE,STDLIB,EXAMPLE_PYTHONPATH,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"


# ------------------------------------------------------------------------------
[tool.mypy]

exclude = ['/test_.*\.py$']

# Use strict as a base, and explicitly remove the checks that we do not want.
strict = true

# There are not type hints in e.g. 'subprocess' which we call a lot.
disallow_untyped_calls = false


[[tool.mypy.overrides]]

module = "tsfpga.examples.modules.*"
strict = false
disallow_untyped_defs = false

[[tool.mypy.overrides]]

module = "tools.*"
strict = false
disallow_untyped_defs = false


# ------------------------------------------------------------------------------
[build-system]

requires = ["setuptools"]
build-backend = "setuptools.build_meta"
