################################################################################
build_id.mode = "r"
build_id.description = "Random build ID that can be used to distinguish between builds."


################################################################################
[resync]

type = "register_array"
array_length = 34


# ------------------------------------------------------------------------------
[resync.data]

mode = "r_wpulse"
