
################################################################################
[register.status]

[register.status.bit.idle]

description = """'1' when the module is inactive and a new run can be launched.

'0' when the module is working."""


[register.status.integer.counter]

description = "Number of AXI bursts that have finished."
max_value = 255


################################################################################
[register.command]

[register.command.bit.start]

description = "Start a read and write cycle."


################################################################################
[register.version]

mode = "r"
description = "Version number for this module"

[register.version.integer.version]

description = "Version field."
max_value = 255


################################################################################
[register_array.addrs]

array_length = 2


# ------------------------------------------------------------------------------
[register_array.addrs.register.read_addr]

mode = "r_w"
description = "Where to read data from."


# ------------------------------------------------------------------------------
[register_array.addrs.register.write_addr]

mode = "r_w"
description = "Where to write data."


################################################################################
[constant.axi_data_width]

value = 64
description = "Data width of the AXI port used by this module."


################################################################################
[constant.burst_length_beats]

value = 16
description = """
The burst length, in number of beats, that will be used by this module.
This value, in conjunction with **axi_data_width** gives the size of the memory buffer that will
be used.
"""
