-- -----------------------------------------------------------------------------
-- This file is automatically generated by hdl-registers version 6.2.1-dev2.
-- Code generator VhdlRegisterPackageGenerator version 1.0.0.
-- Generated 2024-12-30 15:17 from file regs_register_top_level.toml at commit 242d1974bf9d (local changes present).
-- Register hash fba3d99fc88234c570b46cc4db509307bad3423b.
-- -----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.fixed_pkg.all;

library reg_file;
use reg_file.reg_file_pkg.all;


package register_top_level_regs_pkg is

  -- ---------------------------------------------------------------------------
  -- Values of register constants.
  constant register_top_level_constant_num_register_lists : integer := 15;

  -- ---------------------------------------------------------------------------
  -- The valid range of register indexes.
  subtype register_top_level_reg_range is natural range 0 to 19;

  -- Number of times the 'registers' register array is repeated.
  constant register_top_level_registers_array_length : natural := 20;
  -- Range for indexing 'registers' register array repetitions.
  subtype register_top_level_registers_range is natural range 0 to 19;

  -- Register indexes, within the list of registers.
  function register_top_level_registers_reg(
    array_index : register_top_level_registers_range
  ) return register_top_level_reg_range;

  -- Declare 'reg_map' and 'regs_init' constants here but define them in body (deferred constants).
  -- So that functions have been elaborated when they are called.
  -- Needed for ModelSim compilation to pass.

  -- To be used as the 'regs' generic of 'axi_lite_reg_file.vhd'.
  constant register_top_level_reg_map : reg_definition_vec_t(register_top_level_reg_range);

  -- To be used for the 'regs_up' and 'regs_down' ports of 'axi_lite_reg_file.vhd'.
  subtype register_top_level_regs_t is reg_vec_t(register_top_level_reg_range);
  -- To be used as the 'default_values' generic of 'axi_lite_reg_file.vhd'.
  constant register_top_level_regs_init : register_top_level_regs_t;

  -- To be used for the 'reg_was_read' and 'reg_was_written' ports of 'axi_lite_reg_file.vhd'.
  subtype register_top_level_reg_was_accessed_t is std_ulogic_vector(register_top_level_reg_range);

  -- -----------------------------------------------------------------------------
  -- Fields in the 'reg' register within the 'registers' register array.
  -- Range of the 'field' field.
  subtype register_top_level_registers_reg_field is natural range 15 downto 0;
  -- Width of the 'field' field.
  constant register_top_level_registers_reg_field_width : positive := 16;
  -- Type for the 'field' field.
  subtype register_top_level_registers_reg_field_t is u_unsigned(15 downto 0);
  -- Default value of the 'field' field.
  constant register_top_level_registers_reg_field_init : register_top_level_registers_reg_field_t := "0000000000000000";

end package;

package body register_top_level_regs_pkg is

  function register_top_level_registers_reg(
    array_index : register_top_level_registers_range
  ) return register_top_level_reg_range is
  begin
    return 0 + array_index * 1 + 0;
  end function;

  constant register_top_level_reg_map : reg_definition_vec_t(register_top_level_reg_range) := (
    0 => (idx => register_top_level_registers_reg(0), reg_type => r_wpulse),
    1 => (idx => register_top_level_registers_reg(1), reg_type => r_wpulse),
    2 => (idx => register_top_level_registers_reg(2), reg_type => r_wpulse),
    3 => (idx => register_top_level_registers_reg(3), reg_type => r_wpulse),
    4 => (idx => register_top_level_registers_reg(4), reg_type => r_wpulse),
    5 => (idx => register_top_level_registers_reg(5), reg_type => r_wpulse),
    6 => (idx => register_top_level_registers_reg(6), reg_type => r_wpulse),
    7 => (idx => register_top_level_registers_reg(7), reg_type => r_wpulse),
    8 => (idx => register_top_level_registers_reg(8), reg_type => r_wpulse),
    9 => (idx => register_top_level_registers_reg(9), reg_type => r_wpulse),
    10 => (idx => register_top_level_registers_reg(10), reg_type => r_wpulse),
    11 => (idx => register_top_level_registers_reg(11), reg_type => r_wpulse),
    12 => (idx => register_top_level_registers_reg(12), reg_type => r_wpulse),
    13 => (idx => register_top_level_registers_reg(13), reg_type => r_wpulse),
    14 => (idx => register_top_level_registers_reg(14), reg_type => r_wpulse),
    15 => (idx => register_top_level_registers_reg(15), reg_type => r_wpulse),
    16 => (idx => register_top_level_registers_reg(16), reg_type => r_wpulse),
    17 => (idx => register_top_level_registers_reg(17), reg_type => r_wpulse),
    18 => (idx => register_top_level_registers_reg(18), reg_type => r_wpulse),
    19 => (idx => register_top_level_registers_reg(19), reg_type => r_wpulse)
  );

  constant register_top_level_regs_init : register_top_level_regs_t := (
    0 => "00000000000000000000000000000000",
    1 => "00000000000000000000000000000000",
    2 => "00000000000000000000000000000000",
    3 => "00000000000000000000000000000000",
    4 => "00000000000000000000000000000000",
    5 => "00000000000000000000000000000000",
    6 => "00000000000000000000000000000000",
    7 => "00000000000000000000000000000000",
    8 => "00000000000000000000000000000000",
    9 => "00000000000000000000000000000000",
    10 => "00000000000000000000000000000000",
    11 => "00000000000000000000000000000000",
    12 => "00000000000000000000000000000000",
    13 => "00000000000000000000000000000000",
    14 => "00000000000000000000000000000000",
    15 => "00000000000000000000000000000000",
    16 => "00000000000000000000000000000000",
    17 => "00000000000000000000000000000000",
    18 => "00000000000000000000000000000000",
    19 => "00000000000000000000000000000000"
  );

end package body;
