################################################################################
[registers]

type = "register_array"
array_length = 2


# ------------------------------------------------------------------------------
[registers.reg]

mode = "r_w"

field.type = "bit_vector"
field.width = 16


################################################################################
[num_register_lists]

type = "constant"
value = 4
