################################################################################
[registers]

type = "register_array"
array_length = 20


# ------------------------------------------------------------------------------
[registers.registers]

mode = "r_wpulse"

field.type = "bit_vector"
field.width = 16


################################################################################
[num_register_lists]

type = "constant"
value = 15
